

export const ADD_TODO = "ADD_TODO";

export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESSS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESSS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

